export const DEMO_USER = {
  id: 'demo-admin',
  name: 'דוד כהן',
  email: 'admin@cohen-law.co.il',
  role: 'ADMIN' as const,
  avatarUrl: null,
}

export const DEMO_USERS = [
  DEMO_USER,
  { id: 'emp-1', name: 'שרה לוי', email: 'sara@cohen-law.co.il', role: 'EMPLOYEE', avatarUrl: null },
  { id: 'emp-2', name: 'אבי שפירא', email: 'avi@cohen-law.co.il', role: 'EMPLOYEE', avatarUrl: null },
]

export const DEMO_CASES = [
  {
    id: 'case-1',
    caseNumber: '2024-48291',
    title: 'כהן נ׳ שות׳ יצוא — תביעה חוזית',
    clientName: 'משה כהן',
    clientEmail: 'moshe@example.com',
    clientPhone: '050-1234567',
    status: 'IN_PROGRESS',
    caseType: 'מסחרי',
    description: 'תביעה בגין הפרת חוזה סחר. הלקוח מבקש פיצויים בסך 500,000 ש"ח.',
    courtDate: new Date(Date.now() + 7 * 86400000).toISOString(),
    courtName: 'בית משפט המחוזי תל אביב',
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    assignments: [
      { userId: 'demo-admin', user: { id: 'demo-admin', name: 'דוד כהן', avatarUrl: null } },
      { userId: 'emp-1', user: { id: 'emp-1', name: 'שרה לוי', avatarUrl: null } },
    ],
    tasks: [],
    documents: [],
    _count: { tasks: 3, documents: 2 },
  },
  {
    id: 'case-2',
    caseNumber: '2024-33105',
    title: 'גירושין — לוי-שפירא',
    clientName: 'רחל לוי',
    clientEmail: null,
    clientPhone: '052-7654321',
    status: 'OPEN',
    caseType: 'משפחה',
    description: 'תיק גירושין. חלוקת רכוש ומשמורת ילדים.',
    courtDate: null,
    courtName: null,
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    assignments: [
      { userId: 'emp-2', user: { id: 'emp-2', name: 'אבי שפירא', avatarUrl: null } },
    ],
    tasks: [],
    documents: [],
    _count: { tasks: 1, documents: 0 },
  },
  {
    id: 'case-3',
    caseNumber: '2024-71843',
    title: 'ירושה — עיזבון שפירא',
    clientName: 'יוסף שפירא',
    clientEmail: 'yosef@example.com',
    clientPhone: '054-9876543',
    status: 'PENDING_COURT',
    caseType: 'אזרחי',
    description: 'תיק ירושה. חלוקת עיזבון בין 4 יורשים.',
    courtDate: new Date(Date.now() + 14 * 86400000).toISOString(),
    courtName: 'בית משפט לענייני משפחה ירושלים',
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    assignments: [
      { userId: 'demo-admin', user: { id: 'demo-admin', name: 'דוד כהן', avatarUrl: null } },
    ],
    tasks: [],
    documents: [],
    _count: { tasks: 2, documents: 5 },
  },
  {
    id: 'case-4',
    caseNumber: '2023-99201',
    title: 'תאונת דרכים — בן דוד',
    clientName: 'אורי בן דוד',
    clientEmail: 'uri@example.com',
    clientPhone: '053-1122334',
    status: 'CLOSED',
    caseType: 'אזרחי',
    description: 'תביעת פיצויים בגין נזקי גוף בתאונת דרכים.',
    courtDate: null,
    courtName: null,
    createdAt: new Date(Date.now() - 180 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    assignments: [
      { userId: 'emp-1', user: { id: 'emp-1', name: 'שרה לוי', avatarUrl: null } },
    ],
    tasks: [],
    documents: [],
    _count: { tasks: 0, documents: 3 },
  },
]

export const DEMO_TASKS = [
  {
    id: 'task-1',
    title: 'הכנת כתב תביעה',
    description: 'הכן את כתב התביעה לבית המשפט המחוזי',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    dueDate: new Date(Date.now() + 3 * 86400000).toISOString(),
    caseId: 'case-1',
    assigneeId: 'emp-1',
    createdById: 'demo-admin',
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    assignee: { id: 'emp-1', name: 'שרה לוי', avatarUrl: null },
    createdBy: { id: 'demo-admin', name: 'דוד כהן' },
    case: { id: 'case-1', caseNumber: '2024-48291', title: 'כהן נ׳ שות׳ יצוא' },
  },
  {
    id: 'task-2',
    title: 'איסוף מסמכים ראייתיים',
    description: 'איסוף כל החוזים והתכתובות הרלוונטיות',
    status: 'TODO',
    priority: 'MEDIUM',
    dueDate: new Date(Date.now() + 7 * 86400000).toISOString(),
    caseId: 'case-1',
    assigneeId: 'emp-1',
    createdById: 'demo-admin',
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    assignee: { id: 'emp-1', name: 'שרה לוי', avatarUrl: null },
    createdBy: { id: 'demo-admin', name: 'דוד כהן' },
    case: { id: 'case-1', caseNumber: '2024-48291', title: 'כהן נ׳ שות׳ יצוא' },
  },
  {
    id: 'task-3',
    title: 'פגישה עם הלקוח',
    description: 'עדכון הלקוח על מצב התיק',
    status: 'TODO',
    priority: 'URGENT',
    dueDate: new Date(Date.now() - 1 * 86400000).toISOString(),
    caseId: 'case-2',
    assigneeId: 'emp-2',
    createdById: 'demo-admin',
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    assignee: { id: 'emp-2', name: 'אבי שפירא', avatarUrl: null },
    createdBy: { id: 'demo-admin', name: 'דוד כהן' },
    case: { id: 'case-2', caseNumber: '2024-33105', title: 'גירושין — לוי-שפירא' },
  },
  {
    id: 'task-4',
    title: 'הגשת בקשה לדחיית דיון',
    description: '',
    status: 'DONE',
    priority: 'HIGH',
    dueDate: new Date(Date.now() - 10 * 86400000).toISOString(),
    caseId: 'case-3',
    assigneeId: 'demo-admin',
    createdById: 'demo-admin',
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    assignee: { id: 'demo-admin', name: 'דוד כהן', avatarUrl: null },
    createdBy: { id: 'demo-admin', name: 'דוד כהן' },
    case: { id: 'case-3', caseNumber: '2024-71843', title: 'ירושה — עיזבון שפירא' },
  },
]

export const DEMO_SETTINGS = {
  id: 'singleton',
  firmName: 'כהן ושות׳ — עורכי דין',
  primaryColor: '#1e40af',
  firmLogo: null,
  emailFrom: 'office@cohen-law.co.il',
  phone: '03-1234567',
  address: 'רחוב הרצל 1, תל אביב',
}
